"""crm sync: crm_connections, synced_contacts, retrain_events, trained_models.baseline

Revision ID: a2e481851e6c
Revises: 2b4a399d67e1
Create Date: 2026-09-12 17:23:55.771615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e481851e6c'
down_revision: Union[str, Sequence[str], None] = '2b4a399d67e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_connections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('original_baseline', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_connections_is_active'), 'crm_connections', ['is_active'], unique=False)
    op.create_index(op.f('ix_crm_connections_user_id'), 'crm_connections', ['user_id'], unique=False)
    op.create_table('synced_contacts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('connection_id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('source_modified_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('churned', sa.SmallInteger(), nullable=True),
    sa.Column('is_labelled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['crm_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'external_id', name='uq_synced_contacts_connection_external')
    )
    op.create_index(op.f('ix_synced_contacts_connection_id'), 'synced_contacts', ['connection_id'], unique=False)
    op.create_index('ix_synced_contacts_connection_synced_at', 'synced_contacts', ['connection_id', 'synced_at'], unique=False)
    op.create_index(op.f('ix_synced_contacts_is_labelled'), 'synced_contacts', ['is_labelled'], unique=False)
    op.create_table('retrain_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('connection_id', sa.String(length=32), nullable=False),
    sa.Column('trained_model_id', sa.String(length=32), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('trigger_reason', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('max_psi', sa.Float(), nullable=True),
    sa.Column('mean_psi', sa.Float(), nullable=True),
    sa.Column('per_feature_psi', sa.JSON(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('labelled_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['crm_connections.id'], ),
    sa.ForeignKeyConstraint(['trained_model_id'], ['trained_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrain_events_connection_id'), 'retrain_events', ['connection_id'], unique=False)
    op.create_index(op.f('ix_retrain_events_triggered_at'), 'retrain_events', ['triggered_at'], unique=False)
    op.add_column('trained_models', sa.Column('baseline', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trained_models', 'baseline')
    op.drop_index(op.f('ix_retrain_events_triggered_at'), table_name='retrain_events')
    op.drop_index(op.f('ix_retrain_events_connection_id'), table_name='retrain_events')
    op.drop_table('retrain_events')
    op.drop_index(op.f('ix_synced_contacts_is_labelled'), table_name='synced_contacts')
    op.drop_index('ix_synced_contacts_connection_synced_at', table_name='synced_contacts')
    op.drop_index(op.f('ix_synced_contacts_connection_id'), table_name='synced_contacts')
    op.drop_table('synced_contacts')
    op.drop_index(op.f('ix_crm_connections_user_id'), table_name='crm_connections')
    op.drop_index(op.f('ix_crm_connections_is_active'), table_name='crm_connections')
    op.drop_table('crm_connections')
    # ### end Alembic commands ###
